### ISSUE TITLE
Warning: Module AudioRecorderManager requires main queue setup...

### ISSUE THREAD

**Issue by keithj0nes** [jsierles/react-native-audio#283]
### Tell us which versions you are using ( you can see the versions in your package.json ):

react-native-audio :  ^4.1.3
react-native : 0.56.0
react :  16.4.1
using react-native-sound ? No

I'm getting this warning:

 `Module AudioRecorderManager requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.  `

It displays even if I'm not on the screen that's using react-native-audio. Is there an easy fix for this that I'm not aware of?

![simulator screen shot - iphone 6 - 2018-09-18 at 18 55 47](https://user-images.githubusercontent.com/5441674/45721029-7d71a380-bb74-11e8-80c0-85343d40ab04.png)

Thanks

**Comment by jsierles** [comment]
This is a known issue - will be fixed in the next release. It shouldn't affect behavior.

**Comment by keithj0nes** [comment]
Thanks for the quick reply. It doesn't seem to affect behavior, but the warning sign popping up when showing people on the team doesn't look good, lol. Excited for the next release!

**Comment by diennguyentien** [comment]
You can refer to here: https://www.youtube.com/watch?v=tDVFfMZDoDc

**Comment by keithj0nes** [comment]
@diennguyentien 
Finally got around to getting to your video, and it worked! No clue what you did, but just glad that yellow warning isn't popping up anymore. Thanks!

**Comment by StevenMasini** [comment]
@jsierles This issue isn't fixed yet. I am using 4.2.2 which is the last release so far and this warning is still triggered when I launch my app.

@diennguyentien Why not submit a Pull Request to integrate the fix you made in the video ?

**Comment by pkhodaveissi** [comment]
not fixed in 4.3, just annoying to see it every single time

**Comment by mrozbarry** [comment]
Should be fixed in #315, but hasn't been released.

**Comment by muhammadwfa** [comment]
this warning still exists
 "react-native-audio": "^4.3.0",

**Comment by ramon90** [comment]
Did anyone find a fix?

**Comment by WillTinney** [comment]
It's hacky but you can manually add `+ (BOOL)requiresMainQueueSetup {  return YES; }` in the AudioRecorderManager.m file if the warning is really annoying you.

As @mrozbarry said, it looks like this fix was added in [#315](https://github.com/jsierles/react-native-audio/pull/315) but hasn't been released yet

**Comment by Under-Warz** [comment]
@diennguyentien a PR with your fix would be welcome :) warning still exists as @muhammadwfa mentionned.

**Comment by Rizaldinurm** [comment]
"react-native-audio": "^4.3.0",
still i have this warning

**Comment by muhammadwafa** [comment]
This warning still exists

**Comment by muhammadwafa** [comment]
**author say:**

_This project is no longer actively maintained by me, the original author. I will not be answering issues or merging any more PRs. If someone is interested in taking over the library permanently, let me know!_

**Comment by pratius** [comment]
Same Issues: In latest version "**react-native-audio": "^4.3.0**"
warn][tid:main][RCTModuleData.mm:68] Module AudioRecorderManager requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.


iOS app is getting crashed this not warning.

I follow the same step from :- `https://github.com/jsierles/react-native-audio
 `

Any update please
