### ISSUE TITLE
undefined is not an object (evaluating 'AudioRecorderManager.checkAuthorizationStatus') - android

### ISSUE THREAD

**Issue by cavilaho** [jsierles/react-native-audio#89]
Got this error when executing AudioExample on Android. 

This, added to the response of `react-native link react-native-audio` which is `rnpm-link info iOS module react-native-audio is already linked` makes me think that the example is not runneable on Android. 

Any ideas?

**Comment by RakanNimer** [comment]
Hey !
Thanks for reporting this. I updated the example code, can you try again and report back ?

**Comment by jsierles** [comment]
Fixed in #91.

**Comment by cavilaho** [comment]
Solved. Thanks so much.

**Comment by neilsarkar** [comment]
In case anyone else is new to react-native and doesn't realize this, you need to restart (either via `react-native run-ios` or `react-native run-android` or through the IDEs) after doing `react-native link react-native-audio` -- the js reloading won't pick up the newly linked native libraries.

**Comment by bruckmatthew** [comment]
This issue seems to still persist unless i'm missing something?

![undefined](https://cloud.githubusercontent.com/assets/16609596/22537729/fee99eb4-e960-11e6-8dfe-176930e5d341.png)

React Native 0.40
react-native-audio 3.10.8

added permission to AndroidManifest.xml

Below is the code snippet which I think it might be having problems with.

import {
	Platform,
	PermissionsAndroid,
} from 'react-native';
import { AudioRecorder, AudioUtils } from 'react-native-audio';

class RecordScene extends Component {

    state = {
      currentTime: 0.0,
      recording: false,
      finished: false,
      //Must change back to DocumentDirectoryPath for release. However no directory path 
      audioPath: AudioUtils.MusicDirectoryPath + '/test.aac',
      hasPermission: undefined,
    };

	prepareRecordingPath(audioPath){
	    AudioRecorder.prepareRecordingAtPath(audioPath, {
	        SampleRate: 22050,
	        Channels: 1,
	        AudioQuality: "Low",
	        AudioEncoding: "aac",
	        AudioEncodingBitRate: 32000
	    });
    }

    componentDidMount() {
      this._checkPermission().then((hasPermission) => {
        this.setState({ hasPermission });

        if (!hasPermission) return;

        };
      });
    }

    _checkPermission() {
      if (Platform.OS !== 'android') {
        return Promise.resolve(true);
      }

	  const rationale = {
	    'title': 'Microphone Permission',
	    'message': 'AudioExample needs access to your microphone so you can record audio.'
	  };

      return PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.RECORD_AUDIO, rationale)
        .then((result) => {
          console.log('Permission result:', result);
          return (result === true || result === PermissionsAndroid.RESULTS.GRANTED);
        });
    }

    _record() {
    	this.prepareRecordingPath(this.state.audioPath);
    	AudioRecorder.startRecording();
    	this.setState({recording: true});
    }

**Comment by TechGuyVN** [comment]
I got the same problem, can you solve it?

**Comment by HolaMan** [comment]
I got the same problem.
RN 0.44
react-native-audio 3.2.2

**Comment by ybalaev1** [comment]
react-native link react-native-audio 
cd ios && pod install && cd ..
delete app in your device 
react-native run-ios 
close the terminal with starting the server 
react-native start --reset-cache
